const Array_Movies=
[
      {
        "title": "Inception",
        "year": 2010,
        "director": "Christopher Nolan",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "rating": 8.8,
        "cast": ["Leonardo DiCaprio", "Joseph Gordon-Levitt"],
        "plot": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
        "poster": "inception.jpg",
        "trailer": "https://www.youtube.com/embed/YoHD9XEInc0",
        "duration": 148,
        "country": "United States",
        "language": "English",
        "poster": "https://th.bing.com/th/id/OIP.saLFP388_ITnzfhw0m3rcAHaLH?pid=ImgDet&rs=1"
      },
      {
        "title": "The Green Knight",
        "year": 2021,
        "director": "David Lowery",
        "genres": ["Adventure", "Drama", "Fantasy"],
        "rating": 6.7,
        "cast": ["Dev Patel", "Alicia Vikander", "Joel Edgerton"],
        "plot": "A fantasy retelling of the medieval story of Sir Gawain and the Green Knight.",
        "poster": "the_green_knight.jpg",
        "trailer": "https://www.youtube.com/embed/VoJc2tH3WBw",
        "duration": 130,
        "country": "United States",
        "language": "English",
        "poster": "https://th.bing.com/th/id/OIP.apNjfV_Gz830dHOhtai4UgHaJQ?pid=ImgDet&rs=1"
      },
      {
        "title": "Forrest Gump",
        "year": 1994,
        "director": "Robert Zemeckis",
        "genres": ["Drama", "Romance"],
        "rating": 8.8,
        "cast": ["Tom Hanks", "Robin Wright"],
        "plot": "The presidencies of Kennedy to Nixon, Vietnam, Watergate, and other history unfold through the perspective of an Alabama man with an IQ of 75.",
        "poster": "forrest_gump.jpg",
        "trailer": "https://www.youtube.com/embed/uPIEn0M8su0",
        "duration": 142,
        "country": "United States",
        "language": "English",
        "poster": "https://th.bing.com/th/id/OIP.Lj3qE6dtkVgScNEltpNuJQHaK3?pid=ImgDet&rs=1"
      },
      {
        "title": "The Lord of the Rings: The Fellowship of the Ring",
        "year": 2001,
        "director": "Peter Jackson",
        "genres": ["Action", "Adventure", "Drama"],
        "rating": 8.8,
        "cast": ["Elijah Wood", "Ian McKellen"],
        "plot": "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
        "poster": "lotr_fellowship.jpg",
        "trailer": "https://www.youtube.com/embed/V75dMMIW2B4",
        "duration": 178,
        "country": "United States",
        "language": "English",
        "poster": "https://th.bing.com/th/id/OIP.igRq1TrXoV8_M-6GB91o1gHaLH?pid=ImgDet&rs=1"
      },
      {
        "title": "The Shawshank Redemption",
        "year": 1994,
        "director": "Frank Darabont",
        "genres": ["Drama", "Crime"],
        "rating": 9.3,
        "cast": ["Tim Robbins", "Morgan Freeman"],
        "plot": "Two imprisoned men bond over several years, finding solace and eventual redemption through acts of common decency.",
        "poster": "shawshank_redemption.jpg",
        "trailer": "https://www.youtube.com/embed/6hB3S9bIaco",
        "duration": 142,
        "country": "United States",
        "language": "English",
        "poster": "https://th.bing.com/th/id/R.852d2f6a2c873493d13fee5843fab817?rik=RrTJMPCkAOt6tQ&riu=http%3a%2f%2fwww.reelworldtheology.com%2fwp-content%2fuploads%2f2018%2f08%2fthe-shawshank-redemption-movie-poster-29x41-in-r2000-franck-darabont-tim-robbins.jpg&ehk=NgeHxlYon0p8Yeqwf9xQ7W3FWlEVZn4vT7FR6v1V0us%3d&risl=&pid=ImgRaw&r=0"
      },
      {
        "title": "The Godfather",
        "year": 1972,
        "director": "Francis Ford Coppola",
        "genres": ["Crime", "Drama"],
        "rating": 9.2,
        "cast": ["Marlon Brando", "Al Pacino"],
        "plot": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        "poster": "the_godfather.jpg",
        "trailer": "https://www.youtube.com/embed/sY1S34973zA",
        "duration": 175,
        "country": "United States",
        "language": "English",
        "poster": "https://th.bing.com/th/id/OIP.kFoQMx6RcqljPcWSzzFUogHaLT?pid=ImgDet&rs=1"
      },
      {
        "title": "The Dark Knight",
        "year": 2008,
        "director": "Christopher Nolan",
        "genres": ["Action", "Crime", "Drama"],
        "rating": 9.0,
        "cast": ["Christian Bale", "Heath Ledger"],
        "plot": "When the menace known as The Joker emerges from his mysterious past, the Dark Knight must confront his greatest nemesis.",
        "poster": "the_dark_knight.jpg",
        "trailer": "https://www.youtube.com/embed/EXeTwQWrcwY",
        "duration": 152,
        "country": "United States",
        "language": "English",
        "poster": "https://th.bing.com/th/id/R.7858584e0e540252618d7bfb1ef46804?rik=pde7ZIE3QaH7Ig&riu=http%3a%2f%2fhost.trivialbeing.org%2fup%2ftdk-may17-joker-poster-large.jpg&ehk=g8dnVbBCb1VT%2fO9yUlm0aTB9RfEQ80PTB1aYTenHrKs%3d&risl=&pid=ImgRaw&r=0"
      },
      {
        "title": "Pulp Fiction",
        "year": 1994,
        "director": "Quentin Tarantino",
        "genres": ["Crime", "Drama"],
        "rating": 8.9,
        "cast": ["John Travolta", "Samuel L. Jackson"],
        "plot": "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        "poster": "pulp_fiction.jpg",
        "trailer": "https://www.youtube.com/embed/s7EdQ4FqbhY",
        "duration": 154,
        "country": "United States",
        "language": "English",
        "poster": "https://th.bing.com/th/id/R.c2b0e8fc2683c01832134477c96ea6d8?rik=GzfJFvzM9AS2tw&pid=ImgRaw&r=0"
      },
      {
        "title": "Dune",
        "year": 2021,
        "director": "Denis Villeneuve",
        "genres": ["Adventure", "Sci-Fi"],
        "rating": 7.9,
        "cast": ["Timothée Chalamet", "Rebecca Ferguson", "Zendaya"],
        "plot": "A young nobleman named Paul Atreides leads a rebellion to reclaim his family's control over the desert planet Arrakis.",
        "poster": "dune.jpg",
        "trailer": "https://www.youtube.com/embed/8g18jFHCLXk",
        "duration": 155,
        "country": "United States",
        "language": "English",
        "poster": "https://image.tmdb.org/t/p/original/ngUaHgSZGkKy1Izwjk7qwZLOC5A.jpg"
      },      
      {
        "title": "The Midnight Sky",
        "year": 2020,
        "director": "George Clooney",
        "genres": ["Sci-Fi", "Drama", "Thriller"],
        "rating": 6.1,
        "cast": ["George Clooney", "Felicity Jones", "David Oyelowo"],
        "plot": "A lone scientist in the Arctic races to contact a crew of astronauts returning home to a mysterious global catastrophe.",
        "poster": "the_midnight_sky.jpg",
        "trailer": "https://www.youtube.com/embed/C7kFfR_vXhI",
        "duration": 118,
        "country": "United States",
        "language": "English",
        "poster": "https://th.bing.com/th/id/R.4d14a460bf589b5e33cf996a6c728f90?rik=fImdnqEH7lTdNA&pid=ImgRaw&r=0"
      },
      {
        "title": "Promising Young Woman",
        "year": 2020,
        "director": "Emerald Fennell",
        "genres": ["Crime", "Drama", "Thriller"],
        "rating": 7.5,
        "cast": ["Carey Mulligan", "Bo Burnham", "Alison Brie"],
        "plot": "A young woman seeks to avenge the death of her best friend by confronting those who wronged her.",
        "poster": "promising_young_woman.jpg",
        "trailer": "https://www.youtube.com/embed/7i5kiFDunk8",
        "duration": 113,
        "country": "United States",
        "language": "English",
        "poster": "https://th.bing.com/th/id/OIP.5gXzxdGkiRrfx0IggkPVXwAAAA?pid=ImgDet&rs=1"
      }
    ]
    export default Array_Movies;